### ISSUE TITLE
You might add the Forest Othello program to your list

### ISSUE THREAD

**Issue by Marmotte06** [sensuikan1973/othello-complete-analysis#1]
Hi Sensuikan, I see you are gathering and listing all the good Othello programs in your work.
You might want to add the Forest program I developed, which uses the latest neural network technologies and plays quite well.
Here is the link:
https://ocasile.pagesperso-orange.fr/forest.htm

Olivier

**Comment by sensuikan1973** [comment]
Hi, @Marmotte06

Thanks !! I will see your good program.

btw, Would you allow me to translate your [article](https://ocasile.pagesperso-orange.fr/neurone.htm) to Japanese and publish ?

In addition, source code is public ?

Regards,

**Comment by Marmotte06** [comment]
Hi Sensuikan,
Nop, I haven't made the source code public so far. Maybe I will do it one day, but I would first need to translate all the code and comments from French to English and that's a huge task. Perhaps however I will publish some of the key algorithms, I will see.
I saw your questions regarding the translation of my explanations on the program. I am OK with that but please wait a bit, because I have made lots of progress during the past year and some paragraphs need to be rewritten to reflect those progress. It's really incredible how much you can progress with neural networks when you start to understand all the possibilities.
Olivier

**Comment by sensuikan1973** [comment]
Thanks! ,and I'm really looking forward to that.

I added the description of FOREST on README.
https://github.com/sensuikan1973/othello-complete-analysis#%E5%8F%82%E8%80%83

**Comment by sensuikan1973** [comment]
📝 translation.

https://ocasile.pagesperso-orange.fr/neurone.htm
→ https://github.com/sensuikan1973/othello-complete-analysis/tree/main/translations/Developing_an_Artificial_Intelligence_for_Othello
